StudentMVC/Controllers/StudentBooksDetailsController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;

using BLL.Services.StudentBookService;

namespace StudentMVC.Controllers;

[Route("[controller]/[action]")]
public class StudentBooksDetailsController : Controller
{
   private readonly IStudentBookDetails _studentBookDetails;
    public StudentBooksDetailsController(IStudentBookDetails studentBookDetails) {
       _studentBookDetails = studentBookDetails;
    }


    [HttpGet]
    public async Task<IActionResult> Index()
    {
        return View("~/Views/Student/IndexStudentBookDetails.cshtml");
    }
    [HttpGet]
    public async Task<IActionResult> Get(DataSourceLoadOptions loadOptions)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }
        try
        {
            var result = await _studentBookDetails.StudentBookDetails();
            return Json(DataSourceLoader.Load(result, loadOptions));
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"An unexpected error occurred: {ex.Message}");
        }
    }

    //    [HttpPost]
    //    public async Task<IActionResult> Post(string values) {
    //        var model = new Book();
    //        var valuesDict = JsonConvert.DeserializeObject<IDictionary>(values);
    //        PopulateModel(model, valuesDict);

    //        if(!TryValidateModel(model))
    //            return BadRequest(GetFullErrorMessage(ModelState));

    //        var result = _context.Books.AddAsync(model);
    //        await _context.SaveChangesAsync();

    //        return Json(new { result.Entity.BookId });
    //    }

    //    [HttpPut]
    //    public async Task<IActionResult> Put(int key, string values) {
    //        var model = await _context.Books.FirstOrDefaultAsync(item => item.BookId == key);
    //        if(model == null)
    //            return StatusCode(409, "Object not found");

    //        var valuesDict = JsonConvert.DeserializeObject<IDictionary>(values);
    //        PopulateModel(model, valuesDict);

    //        if(!TryValidateModel(model))
    //            return BadRequest(GetFullErrorMessage(ModelState));

    //        await _context.SaveChangesAsync();
    //        return Ok();
    //    }

    //    [HttpDelete]
    //    public async Task Delete(int key) {
    //        var model = await _context.Books.FirstOrDefaultAsync(item => item.BookId == key);

    //        _context.Books.Remove(model);
    //        await _context.SaveChangesAsync();
    //    }


    //    private void PopulateModel(Book model, IDictionary values) {
    //        string BOOK_ID = nameof(Book.BookId);
    //        string AUTHOR = nameof(Book.Author);
    //        string TITLE = nameof(Book.Title);
    //        string GENRE = nameof(Book.Genre);
    //        string PRICE = nameof(Book.Price);
    //        string CREATED_DATE_TIME = nameof(Book.CreatedDateTime);
    //        string CREATED_BY = nameof(Book.CreatedBy);
    //        string MODIFIED_DATE_TIME = nameof(Book.ModifiedDateTime);
    //        string MODIFIED_BY = nameof(Book.ModifiedBy);

    //        if(values.Contains(BOOK_ID)) {
    //            model.BookId = Convert.ToInt32(values[BOOK_ID]);
    //        }

    //        if(values.Contains(AUTHOR)) {
    //            model.Author = Convert.ToString(values[AUTHOR]);
    //        }

    //        if(values.Contains(TITLE)) {
    //            model.Title = Convert.ToString(values[TITLE]);
    //        }

    //        if(values.Contains(GENRE)) {
    //            model.Genre = Convert.ToString(values[GENRE]);
    //        }

    //        if(values.Contains(PRICE)) {
    //            model.Price = values[PRICE] != null ? Convert.ToDecimal(values[PRICE], CultureInfo.InvariantCulture) : (decimal?)null;
    //        }

    //        if(values.Contains(CREATED_DATE_TIME)) {
    //            model.CreatedDateTime = values[CREATED_DATE_TIME] != null ? Convert.ToDateTime(values[CREATED_DATE_TIME]) : (DateTime?)null;
    //        }

    //        if(values.Contains(CREATED_BY)) {
    //            model.CreatedBy = values[CREATED_BY] != null ? ConvertTo<System.Guid>(values[CREATED_BY]) : (Guid?)null;
    //        }

    //        if(values.Contains(MODIFIED_DATE_TIME)) {
    //            model.ModifiedDateTime = values[MODIFIED_DATE_TIME] != null ? Convert.ToDateTime(values[MODIFIED_DATE_TIME]) : (DateTime?)null;
    //        }

    //        if(values.Contains(MODIFIED_BY)) {
    //            model.ModifiedBy = values[MODIFIED_BY] != null ? ConvertTo<System.Guid>(values[MODIFIED_BY]) : (Guid?)null;
    //        }
    //    }

    //    private T ConvertTo<T>(object value) {
    //        var converter = System.ComponentModel.TypeDescriptor.GetConverter(typeof(T));
    //        if(converter != null) {
    //            return (T)converter.ConvertFrom(null, CultureInfo.InvariantCulture, value);
    //        } else {
    //            // If necessary, implement a type conversion here
    //            throw new NotImplementedException();
    //        }
    //    }

    //    private string GetFullErrorMessage(ModelStateDictionary modelState) {
    //        var messages = new List<string>();

    //        foreach(var entry in modelState) {
    //            foreach(var error in entry.Value.Errors)
    //                messages.AddAsync(error.ErrorMessage);
    //        }

    //        return String.Join(" ", messages);
    //    }
}

StudentMVC/Controllers/StudentController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;
using BLL.Services.StudentService;
using BLL.StudentDto;
using Newtonsoft.Json;
using System.Collections;
using System.Runtime.InteropServices;
using Microsoft.Extensions.Caching.Memory;

namespace StudentMVC.Controllers;

[Route("[controller]/[action]")]
public class StudentController : Controller
{
    private  readonly IStudentService _studentService;
    private readonly IMemoryCache _memoryCache;
    private readonly string CachKey = "CachStudentKey";
    public StudentController(IStudentService studentService, IMemoryCache memoryCache)
    {
        _studentService = studentService;
        _memoryCache = memoryCache;
    }

    [HttpGet]
    public async   Task<IActionResult> Index()
    {
        //const int pageSize = 5;
        //if (pg < 1) pg = 1;
        //int recsCount = students.Count();
        //Pager pager = new Pager(recsCount, pg, pageSize);
        //int reskip = (pg - 1) * pageSize;
        //var data = students.Skip(reskip).Take(pager.PageSize).ToList();
        //ViewBag.Pager = pager;
            return View();
    }
    [HttpPost]
    public async Task<IActionResult> BookMenagment(int StudentId, int BookId, [Optional]DateTime? DateTime) 
    {
        try
        {
            if (DateTime is null)
            {
                var takebook = await _studentService.TakeBook(StudentId, BookId);
                return  Json(new { succes = true, message = $"Your taken book successesfuly" });
            };
            
            var returnbook = await _studentService.ReturningBook(StudentId, BookId, (DateTime)DateTime);
            return Json(new { succes = true, message =$"Your returned book successesfuly" });
        }
        catch (UserFriendlyException ex)
        {
            return Json(new { success = false, message = $"{ex.Message}" });
        }
        catch (Exception ex)
        {
            return Json(new { succes = false, message = $"{StatusCode(500, ex.Message)}" });
        }
    }

    [HttpGet]
    public async Task<IActionResult> Get(DataSourceLoadOptions loadOptions)
    {
        var students = await _studentService.GetStudentAsync();
        return Json(DataSourceLoader.Load(students, loadOptions));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Post(string values)
    {
        if (ModelState.IsValid) return BadRequest(ModelState); 
        try
        {
            var valuesDict = JsonConvert.DeserializeObject<StudentDTO>(values);
            if (!TryValidateModel(valuesDict))
                return BadRequest(ModelState);
            if (ModelState.IsValid)
            {
                await _studentService.AddStudentAsync(valuesDict);
            }
            return Json(new { success = true, message = $"Student Added successfully" });
        }
        catch (ExceptionHandler ex) 
        {
            return Json(new { success = false,message = $"Failed  add student. Error: {ex.Message}" });
        }
    }

    [HttpPut]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Put(int key,string values)
    {
        if (ModelState.IsValid) return BadRequest(ModelState);
        try
        {
            var model = await _studentService.GetByIdAsync(key);
            if (model == null)
                return StatusCode(409, "Object not found");
            var valuesDict = JsonConvert.DeserializeObject<IDictionary>(values);
            if (ModelState.IsValid)
            {
                PopulateModel(model, valuesDict);
                await _studentService.UpgradeStudentAsync(model);
            }
            return Json(new {success=true, message = $"student updated succes" });
        } 
        catch (ExceptionHandler ex) 
        {
            return Json(new { success = false, message = $"Failed to update student. Error: {ex.Message}" });
        }
        catch 
        {
            return BadRequest(ModelState);
        }   
    }

    [HttpDelete]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int key)
    {

        try 
        { 
        
                var deleted = await _studentService.DeleteStudentAsync(key);
                return Json(new { success = true, message = "Student delete successfully." });
        }
        catch (ExceptionHandler ex)
        {
            return Json(new { success = false, message = $"Failed to delete student. Error: {ex.Message}" });
        }
        catch (Exception ex)
        {
            return Json(new { success = false, message = $"Failed to delete student. Error: {ex.Message}" });
        }


    }


    



    private void PopulateModel(StudentDTO model, IDictionary values)
    {
        string STUDENT_ID = nameof(StudentDTO.Id);
        string FIRST_NAME = nameof(StudentDTO.FirstName);
        string LAST_NAME = nameof(StudentDTO.LastName);
        string MIDDLE_NAME = nameof(StudentDTO.MiddleName);
        string TICKET_NUMBER = nameof(StudentDTO.TicketNumber);
        string BIRTH_YEAR = nameof(StudentDTO.BirthYear);
        string BIRTH_PLACE = nameof(StudentDTO.BirthPlace);
        string ADDRESS = nameof(StudentDTO.Address);
        string GENDER = nameof(StudentDTO.Gender);
        string MARITAL_STATUS = nameof(StudentDTO.MaritalStatus);
        string GMAIL = nameof(StudentDTO.Gmail);

        if (values.Contains(STUDENT_ID))
        {
            model.Id = Convert.ToInt32(values[STUDENT_ID]);
        }

        if (values.Contains(FIRST_NAME))
        {
            model.FirstName = Convert.ToString(values[FIRST_NAME]);
        }

        if (values.Contains(LAST_NAME))
        {
            model.LastName = Convert.ToString(values[LAST_NAME]);
        }

        if (values.Contains(MIDDLE_NAME))
        {
            model.MiddleName = Convert.ToString(values[MIDDLE_NAME]);
        }

        if (values.Contains(TICKET_NUMBER))
        {
            model.TicketNumber = Convert.ToString(values[TICKET_NUMBER]);
        }

        if (values.Contains(BIRTH_YEAR))
        {
            model.BirthYear = Convert.ToInt32(values[BIRTH_YEAR]);
        }

        if (values.Contains(BIRTH_PLACE))
        {
            model.BirthPlace = Convert.ToString(values[BIRTH_PLACE]);
        }

        if (values.Contains(ADDRESS))
        {
            model.Address = Convert.ToString(values[ADDRESS]);
        }

        if (values.Contains(GENDER))
        {
            model.Gender = Convert.ToString(values[GENDER]);
        }

        if (values.Contains(MARITAL_STATUS))
        {
            model.MaritalStatus = Convert.ToString(values[MARITAL_STATUS]);
        }
        if (values.Contains(GMAIL))
        {
            model.Gmail = Convert.ToString(values[GMAIL]);
        }
    }

    //    private T ConvertTo<T>(object value)
    //    {
    //        var converter = System.ComponentModel.TypeDescriptor.GetConverter(typeof(T));
    //        if (converter != null)
    //        {
    //            return (T)converter.ConvertFrom(null, CultureInfo.InvariantCulture, value);
    //        }
    //        else
    //        {
    //            If necessary, implement a type conversion here
    //            throw new NotImplementedException();
    //        }
    //    }

    //    private string GetFullErrorMessage(ModelStateDictionary modelState)
    //    {
    //        var messages = new List<string>();

    //        foreach (var entry in modelState)
    //        {
    //            foreach (var error in entry.Value.Errors)
    //                messages.AddAsync(error.ErrorMessage);
    //        }

    //        return String.Join(" ", messages);
    //    }
    //}
    [HttpGet]
    public async Task<IActionResult> AddressesLookup(DataSourceLoadOptions loadOptions)
    {
        var lookup = (await _studentService.GetStudentAsync()).Select(i => new
        {
            Value = i.Id,
            Text = i.Gender + ", " + i.MaritalStatus
        }).OrderBy(i => i.Text).AsQueryable();
        return Json(DataSourceLoader.Load(lookup, loadOptions));
    }

    [HttpGet]
    public IActionResult GenderLookup(DataSourceLoadOptions loadOptions)
    {//todochange in database with field collection 
        var genders = new List<object>
        {
        new { Value = "male", Text = "Male" },
        new { Value = "female", Text = "Female" },
        new { Value = "not specified", Text = "Not Specified" }
         };
        return Json(genders);
    }
    [HttpGet]
    public IActionResult Maritalstatus(DataSourceLoadOptions loadOptions)
    {
        //todochange in database with field collection 
        var marital = new List<object>
    {
        new { Value = "married", Text = "Married" },
        new { Value = "No data", Text = "No data" },
       
    };
        return Json(marital);
    }
}

StudentMVC/Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>StudentMVC</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://unpkg.com/devextreme-quill@23_2/dist/dx-quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">StudentMVC</a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a href="#" class="nav-link active">Home</a></li>
                    <li class="nav-item"><a href="#about" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="#contact" class="nav-link">Contact</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","Student")" class="nav-link">Student</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","StudentBooksDetails")" class="nav-link">StudentBook</a></li>
                   
                </ul>
            </div>s
        </div>
    </nav>

    <main class="container">
        @RenderBody()
    </main>
</body>

</html>

StudentMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>StudentMVC</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://unpkg.com/devextreme-quill@23_2/dist/dx-quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    <link href="~/css/Index.css" rel="stylesheet" />
    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <script src="~/js/site.js"></script>
   
</head>
 @inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions {
    public string GetAntiXsrfRequestToken() => Xsrf.GetAndStoreTokens(Context).RequestToken;
}
<script>
    function grid_dataSource_beforeSend(op, ajax) {
       
        ajax.headers = { RequestVerificationToken: '@GetAntiXsrfRequestToken()' };
    }
</script>
<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">StudentMVC</a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a href="@Url.Action("Index","Student")" class="nav-link">Student</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","StudentBooksDetails")" class="nav-link">StudentBook</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container">
        @RenderBody()
    </main>
</body>

</html>